name: .NET

on:
  push:
    branches: [ main ]
    paths: "**.cs"
  pull_request:
    branches: [ main ]
    paths: "**.cs"
    
  workflow_dispatch:
    
env:
  AzFnAppName: app-ToffeeTiger-nj3jpycb6kws6
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0.x' # set this to the dotnet version to use
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd
      
    #- name: Build
    #  run: dotnet build --no-restore
      
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
      

    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true
        environment: azurecloud
        allow-no-subscriptions: false

    - name: Install Module
      shell: pwsh
      run:  |
        Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
        Install-Module -Name Az.Websites

    - name: Get AzFun Publish Profile
      shell: pwsh
      id: azfnprofile
      run:  |
        $profile = ""
        
        #This returns JSON, whereas we want XML for the next step - so let's use the powershell module instead!
        $profile=az webapp deployment list-publishing-profiles --name $env:AzFnAppName --resource-group gobyers
        
        $profile=Get-AzWebAppPublishingProfile -ResourceGroupName gobyers -Name $env:AzFnAppName
        write-output $profile
        $profile = $profile.Replace("`r", "").Replace("`n", "")
        Write-Output "::set-output name=pubprofile::$profile"
        Remove-Variable profile
        
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: '${{ env.AzFnAppName }}'
        slot-name: 'Production'
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ steps.azfnprofile.outputs.pubprofile }}
  
